assets:
  BTCUSDT:
    active: true
    natal:
      date: "2009-01-03T18:15:05Z"
      location: [0.0, 51.5]
  ETHUSDT:
    active: true
    natal:
      date: "2015-07-30T03:26:13Z"
      location: [0.0, 51.5]
  SOLUSDT:
    active: true
    natal:
      date: "2020-03-16T14:29:00Z"
      location: [0.0, 51.5]
  XRPUSDT:
    active: true
    natal:
      date: "2012-06-02T12:00:00Z"
      location: [0.0, 51.5]
